'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PointOfSale.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property add_khaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_khaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property addmblack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addmblack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property addpxblack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addpxblack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property admin_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("admin_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property admin_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("admin_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AdminMedium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AdminMedium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property alertyellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alertyellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowbold_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowbold_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowboldl_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowboldl_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowboldr_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowboldr_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowdownsmall_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowdownsmall_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowt_khakidown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowt_khakidown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowt_khakiup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowt_khakiup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowupsmall_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowupsmall_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property asterisk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("asterisk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backarrow_lkhaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backarrow_lkhaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backarrow_rkhaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backarrow_rkhaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backarrowsmallwhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backarrowsmallwhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backwardcal_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backwardcal_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property basket_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("basket_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bigtickgreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bigtickgreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bkgnd_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bkgnd_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bkgndbottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bkgndbottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonbevelred() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonbevelred", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonbkgnd0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonbkgnd0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonbkgnd01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonbkgnd01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel_khaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel_khaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property canceliconred() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("canceliconred", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancelred() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancelred", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property changepswdlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("changepswdlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property closesale_khaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closesale_khaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property company() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computerone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computerone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ConfigTools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfigTools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property connectionsgray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connectionsgray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property criticalred() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("criticalred", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property crystal() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("crystal", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Customers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Customers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property customers_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("customers_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_khaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_khaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_khaki0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_khaki0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DeleteRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeleteRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deletes_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deletes_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property discount_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("discount_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DODGE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DODGE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property doticongray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doticongray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property doticongreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doticongreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property doticongreen1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doticongreen1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property doticonredicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doticonredicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property downarrowsmallblack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("downarrowsmallblack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property downarrowsmallwhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("downarrowsmallwhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property duoblearrow_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("duoblearrow_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edits_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edits_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit_khaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_khaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f10icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f10icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f10white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f10white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f1icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f1icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f1white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f1white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f2icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f2icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f2white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f2white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f3icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f3icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f3white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f3white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f4icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f4icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f4white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f4white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f5icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f5icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f5white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f5white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f6icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f6icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f6white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f6white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f7icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f7icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f7white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f7white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f8icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f8icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f8white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f8white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f9icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f9icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property f9white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f9white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property floatbal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("floatbal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forwardcal_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forwardcal_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fre3of9x() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("fre3of9x", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property graysquaresamall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("graysquaresamall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property greensquaresmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greensquaresmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property helpask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("helpask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hold_khaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hold_khaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property humanhead() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("humanhead", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info_khaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_khaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property infoblue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("infoblue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property infoiconblue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("infoiconblue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property keys() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keys", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lock_dred() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock_dred", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lockblack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lockblack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loginlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loginlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loginmanager() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loginmanager", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logout_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logout_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logoutmedium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoutmedium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lookup_khaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lookup_khaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property maintenance_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maintenance_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property maximise_blackt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maximise_blackt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minus_khaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minus_khaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minusblack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minusblack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minusM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minusM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property networkwired() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("networkwired", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nextsmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nextsmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property payment_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("payment_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property phone_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phone_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property phone_khaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phone_khaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property planeA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("planeA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property poledisplay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("poledisplay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pos_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pos_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property posbtnbkgnd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("posbtnbkgnd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property posbtnbkgndA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("posbtnbkgndA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property posbtnbkgndB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("posbtnbkgndB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property posbtnbkgndC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("posbtnbkgndC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property posimg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("posimg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property posimgr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("posimgr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property posoff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("posoff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property poson() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("poson", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property previewsmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("previewsmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pricelkup_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pricelkup_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property questionmarkbig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("questionmarkbig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property questionmarksmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("questionmarksmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property questionmedium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("questionmedium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redowhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redowhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redsquaresmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redsquaresmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property report_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property report_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property report2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property roundedcorners() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("roundedcorners", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property roundplusgreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("roundplusgreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property roundplusred() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("roundplusred", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rsicon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("rsicon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property sales_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sales_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search_khaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_khaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Settings2icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings2icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Settingsbig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settingsbig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Settingsicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settingsicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property signalgray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("signalgray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property signalgreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("signalgreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sledge_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sledge_Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smalladd_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smalladd_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallclose_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallclose_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallreload_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallreload_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallreport_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallreport_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smalltickgreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smalltickgreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property systemSettings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("systemSettings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property theRS() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("theRS", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property theSs() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("theSs", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property tickicongreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tickicongreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tickroundsmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tickroundsmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property titlebkgnd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("titlebkgnd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property todaycal_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("todaycal_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tools_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tools_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolsMedium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolsMedium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property triarrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("triarrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property triarrowdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("triarrowdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undowhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undowhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property uparrowsmallblack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uparrowsmallblack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property uparrowsmallwhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uparrowsmallwhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_khaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_khaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warningblue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warningblue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windowclosesmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windowclosesmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zerorate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zerorate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zeroratekhaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zeroratekhaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
